name: Question
description: File a bug report
title: "[Question]: "
labels: ["question"]
assignees:
  - jeroenvandermeulen
body:
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      value: "Ask a question"
    validations:
      required: true
